#ifndef ABDUMESSENGERLIB_GLOBAL_H
#define ABDUMESSENGERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ABDUMESSENGERLIB_LIBRARY)
#  define ABDUMESSENGERLIB_EXPORT Q_DECL_EXPORT
#else
#  define ABDUMESSENGERLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // ABDUMESSENGERLIB_GLOBAL_H
